---
  - name: Change Reg Key For User Shell Folders
    win_pc_registry:
      Ensure: Present
      Force: True
      Key: "HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\User Shell Folders\\"
      ValueName: "{{ item[1].from }}"
      ValueData: "\\\\{{ file_server }}\\c$\\profiles\\{{ item[0].name  }}\\{{ item[1].to }}"
      PsDscRunAsCredential_username: "{{ item[0].name }}"
      PsDscRunAsCredential_password: "{{ item[0].pass }}"
    with_nested:
      - "{{ users }}"
      - "{{ fold_ls }}"
